services:
  p4-dev:
    image: "jinxdh/p4-ubuntu:latest"
    restart: unless-stopped
    privileged: true
    ports:
      - "2222:22"
    volumes:
      - /mnt:/mnt
    command: ["/bin/bash", "-c", "echo 'p4:123' | chpasswd && /usr/sbin/sshd -D"]